#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════╗
║       KUCHLAG INDIA — BACKEND VPS DEPLOYMENT SCRIPT             ║
║       Domain: kuchalagindia.com                                  ║
║       All credentials PRE-FILLED — just run it!                  ║
╚══════════════════════════════════════════════════════════════════╝

Usage:
  1. Upload to VPS:
     scp deploy_backend_vps.py root@YOUR_VPS_IP:/root/

  2. SSH in and run:
     ssh root@YOUR_VPS_IP
     python3 deploy_backend_vps.py
"""

import os
import sys
import subprocess
import time
import secrets
import string

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DOMAIN = "kuchalagindia.com"
DEPLOY_USER = "deploy"
PROJECT_DIR = "/var/www/jwellery"
BACKEND_REPO = "https://github.com/greenhroizon/Render-Jwellery-Application.git"
BACKEND_PORT = 5000

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PRE-FILLED ENVIRONMENT VARIABLES
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Generate a STRONG JWT secret (yours was "secret" which is insecure)
JWT_SECRET = ''.join(secrets.choice(string.ascii_letters + string.digits) for _ in range(64))

ENV_CONTENT = f"""# ═══════════════════════════════════════════════════════
# BACKEND ENV — kuchalagindia.com
# Auto-generated by deploy_backend_vps.py
# ═══════════════════════════════════════════════════════

# ── Server ──
PORT={BACKEND_PORT}
NODE_ENV=production
LOG_LEVEL=production

# ── Database ──
MONGODB_URI=mongodb+srv://kuchalagteam_db_user:WWL9PpXE9Nx4pmuJ@kuchalag.651c2jx.mongodb.net/

# ── JWT ──
JWT_SECRET={JWT_SECRET}
JWT_ALGORITHM=HS256
JWT_EXPIRES_IN=7d

# ── Email (Gmail) ──
EMAIL_SERVICE=gmail
EMAIL_USER=kuchalagteam@gmail.com
EMAIL_PASSWORD=zbzr ampu luur cbed
EMAIL_FROM=noreply@jwellery.com
OTP_EXPIRY_MINUTES=5

# ── AWS S3 ──
AWS_ACCESS_KEY_ID=AKIA4B37UNR3AGCG6QXQ
AWS_SECRET_ACCESS_KEY=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
AWS_S3_BUCKET=kuch-alag-s3
AWS_REGION=ap-south-1

# ── Razorpay ──
RAZORPAY_KEY_ID=rzp_live_SagXbIhpAynO7y
RAZORPAY_KEY_SECRET=d96tSCJI1yidlYDZlbR2geIz

# ── Google Auth ──
GOOGLE_CLIENT_ID=266189706891-kn2efti3o0rj3sk12tm6mip4dq2knc6o.apps.googleusercontent.com
GOOGLE_CLIENT_IDS=266189706891-kn2efti3o0rj3sk12tm6mip4dq2knc6o.apps.googleusercontent.com

# ── CORS (all Vercel frontends + domain) ──
CORS_ORIGIN=https://www.kuchalagindia.com,https://kuchalagindia.com,https://kuchalagindiarepov2.vercel.app,https://jwellery-frontend-next.vercel.app,https://frontend-jwellery-admin-code-so5o.vercel.app,https://frontend-jwellery-admin-code-ywsf.vercel.app,http://localhost:3000

# ── Security ──
ENABLE_HELMET=true
ENABLE_HSTS=true
ENFORCE_HTTPS=true
ALLOW_CREDENTIALS=true

# ── Rate Limiting ──
RATE_LIMIT_MAX_REQUESTS=100
RATE_LIMIT_WINDOW_MS=900000
AUTH_RATE_LIMIT_MAX=20
UPLOAD_RATE_LIMIT_MAX=60
"""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# COLORS & HELPERS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class C:
    R = "\033[91m"; G = "\033[92m"; Y = "\033[93m"; B = "\033[94m"
    M = "\033[95m"; CY = "\033[96m"; BD = "\033[1m"; RS = "\033[0m"

TOTAL_STEPS = 10

def banner():
    print(f"""{C.CY}{C.BD}
    ╔══════════════════════════════════════════════════════════════╗
    ║                                                              ║
    ║      💎  BACKEND VPS DEPLOYMENT — kuchalagindia.com  💎     ║
    ║                                                              ║
    ║      ✅ All credentials PRE-FILLED                           ║
    ║      ✅ MongoDB Atlas (cloud)                                ║
    ║      ✅ Backend only — Frontend & Admin on Vercel            ║
    ║                                                              ║
    ╚══════════════════════════════════════════════════════════════╝
    {C.RS}""")

def step(num, msg):
    print(f"\n{C.BD}{C.G}[{num}/{TOTAL_STEPS}] ▶ {msg}{C.RS}")
    print(f"{C.G}{'─' * 60}{C.RS}")

def info(msg):    print(f"  {C.B}ℹ {msg}{C.RS}")
def ok(msg):      print(f"  {C.G}✅ {msg}{C.RS}")
def warn(msg):    print(f"  {C.Y}⚠️  {msg}{C.RS}")
def err(msg):     print(f"  {C.R}❌ {msg}{C.RS}")

def run(command, check=True, capture=False, cwd=None, env=None):
    print(f"  {C.M}$ {command}{C.RS}")
    merged_env = os.environ.copy()
    if env:
        merged_env.update(env)
    try:
        if capture:
            r = subprocess.run(command, shell=True, check=check,
                               capture_output=True, text=True, cwd=cwd, env=merged_env)
            return r.stdout.strip()
        else:
            subprocess.run(command, shell=True, check=check, cwd=cwd, env=merged_env)
            return True
    except subprocess.CalledProcessError:
        if check:
            err(f"Command failed: {command}")
        return False

def detect_codename():
    try:
        with open("/etc/os-release") as f:
            for line in f:
                if line.startswith("VERSION_CODENAME="):
                    return line.split("=")[1].strip().strip('"')
    except:
        pass
    return "jammy"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# DEPLOYMENT STEPS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def step_01_update():
    step(1, "Updating System Packages")
    run("apt update && apt upgrade -y")
    ok("System updated")


def step_02_install():
    step(2, "Installing Node.js 22, Nginx, PM2, Certbot")

    info("Build tools...")
    run("apt install -y python3 make g++ gcc build-essential curl git ufw")

    info("Node.js 22 LTS...")
    run("curl -fsSL https://deb.nodesource.com/setup_22.x | bash -")
    run("apt install -y nodejs")
    v = run("node -v", capture=True)
    ok(f"Node.js {v}")

    info("PM2...")
    run("npm install -g pm2")
    ok("PM2 installed")

    info("Nginx...")
    run("apt install -y nginx")
    run("systemctl enable nginx")
    run("systemctl start nginx")
    ok("Nginx running")

    info("Certbot...")
    run("apt install -y certbot python3-certbot-nginx")
    ok("Certbot installed")


def step_03_firewall():
    step(3, "Configuring Firewall")
    run("ufw allow OpenSSH")
    run("ufw allow 'Nginx Full'")
    run("echo 'y' | ufw enable", check=False)
    ok("Firewall: SSH + HTTP + HTTPS only")


def step_04_project():
    step(4, "Setting Up Project Directory & Cloning Repo")

    # Create deploy user
    result = run(f"id {DEPLOY_USER}", capture=True, check=False)
    if not result:
        run(f"useradd -m -s /bin/bash {DEPLOY_USER}")
        run(f"usermod -aG sudo {DEPLOY_USER}")
        ok(f"User '{DEPLOY_USER}' created")

    # Create directory
    os.makedirs(PROJECT_DIR, exist_ok=True)
    run(f"chown -R {DEPLOY_USER}:{DEPLOY_USER} {PROJECT_DIR}")

    # Clone backend
    target = os.path.join(PROJECT_DIR, "backend")
    if os.path.exists(os.path.join(target, "server.js")):
        warn("Backend already cloned — pulling latest...")
        run("git pull origin main || git pull origin master", cwd=target, check=False)
    else:
        if os.path.exists(target):
            run(f"rm -rf {target}")
        info("Cloning backend repository...")
        run(f"git clone {BACKEND_REPO} {target}")

    run(f"chown -R {DEPLOY_USER}:{DEPLOY_USER} {PROJECT_DIR}")
    ok(f"Backend cloned to {target}")


def step_05_env():
    step(5, "Creating .env File (Pre-filled)")

    env_path = os.path.join(PROJECT_DIR, "backend", ".env")
    with open(env_path, "w") as f:
        f.write(ENV_CONTENT)
    os.chmod(env_path, 0o600)

    info(f"JWT_SECRET: {JWT_SECRET[:20]}... (auto-generated, 64 chars)")
    info(f"MongoDB: Atlas (kuchalag.651c2jx.mongodb.net)")
    info(f"Email: kuchalagteam@gmail.com")
    info(f"AWS S3: kuch-alag-s3 (ap-south-1)")
    info(f"Razorpay: rzp_live_SagXbIhpAynO7y")
    info(f"CORS: 7 origins (Vercel + domain + localhost)")
    ok(".env created with all credentials")


def step_06_build():
    step(6, "Installing Dependencies & Building")

    backend_dir = os.path.join(PROJECT_DIR, "backend")

    # Add swap if low RAM
    info("Checking memory...")
    try:
        mem = int(run("free -m | awk '/Mem:/ {print $2}'", capture=True))
        if mem < 3072:
            warn(f"Low RAM ({mem}MB) — adding 2GB swap...")
            swap_check = run("swapon --show | grep -c /swapfile", capture=True, check=False)
            if not swap_check or swap_check == "0":
                run("fallocate -l 2G /swapfile")
                run("chmod 600 /swapfile")
                run("mkswap /swapfile")
                run("swapon /swapfile")
                run("grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab")
                ok("2GB swap added")
    except:
        pass

    # Install npm dependencies
    info("npm install (argon2 needs native build — takes ~1 min)...")
    run("npm install --build-from-source=argon2", cwd=backend_dir)
    ok("Dependencies installed")

    # Enable trust proxy in app.js
    info("Enabling trust proxy in app.js...")
    app_js = os.path.join(backend_dir, "app.js")
    try:
        with open(app_js, "r") as f:
            content = f.read()
        if '// app.set("trust proxy", 1);' in content:
            content = content.replace(
                '// app.set("trust proxy", 1);',
                'app.set("trust proxy", 1);'
            )
            with open(app_js, "w") as f:
                f.write(content)
            ok("trust proxy enabled")
        else:
            info("trust proxy already enabled or not found")
    except Exception as e:
        warn(f"Couldn't modify app.js: {e}")

    run(f"chown -R {DEPLOY_USER}:{DEPLOY_USER} {PROJECT_DIR}")


def step_07_pm2():
    step(7, "Starting Backend with PM2")

    backend_dir = os.path.join(PROJECT_DIR, "backend")

    # Stop existing
    run("pm2 delete jwellery-backend", check=False)

    # Start
    info(f"Starting Express.js on port {BACKEND_PORT}...")
    run(f"pm2 start server.js --name jwellery-backend --cwd {backend_dir} "
        f"--max-memory-restart 500M")

    time.sleep(4)
    run("pm2 status")

    # Auto-start on reboot
    info("Configuring auto-start on boot...")
    startup_cmd = run("pm2 startup systemd -u root --hp /root | tail -1", capture=True, check=False)
    if startup_cmd and "sudo" in str(startup_cmd):
        run(startup_cmd, check=False)
    run("pm2 save")

    # Log rotation
    run("pm2 install pm2-logrotate", check=False)
    run("pm2 set pm2-logrotate:max_size 10M", check=False)
    run("pm2 set pm2-logrotate:retain 7", check=False)

    ok("PM2 running with auto-restart on boot")


def step_08_nginx():
    step(8, "Configuring Nginx Reverse Proxy")

    nginx_conf = f"""# ═══════════════════════════════════════════════════════
# {DOMAIN} — Backend API Server
# Frontend & Admin on Vercel
# ═══════════════════════════════════════════════════════

server {{
    listen 80;
    listen [::]:80;
    server_name {DOMAIN} www.{DOMAIN};

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript
               text/xml application/xml text/javascript;

    # Max upload size (product images/videos)
    client_max_body_size 50M;

    # ── All requests → Backend Express.js ──
    location / {{
        proxy_pass http://127.0.0.1:{BACKEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }}
}}
"""
    conf_path = "/etc/nginx/sites-available/jwellery"
    with open(conf_path, "w") as f:
        f.write(nginx_conf)

    enabled = "/etc/nginx/sites-enabled/jwellery"
    if os.path.exists(enabled):
        os.remove(enabled)
    os.symlink(conf_path, enabled)

    default = "/etc/nginx/sites-enabled/default"
    if os.path.exists(default):
        os.remove(default)

    if run("nginx -t", check=False):
        run("systemctl reload nginx")
        ok("Nginx configured and reloaded")
    else:
        err("Nginx config test failed! Run: nginx -t")


def step_09_ssl():
    step(9, "Setting Up SSL (Let's Encrypt)")
    warn("DNS A records must point to this server first!")

    # Check DNS
    info(f"Checking if {DOMAIN} resolves to this server...")
    my_ip = run("curl -s ifconfig.me", capture=True, check=False)
    dns_ip = run(f"dig +short {DOMAIN} | head -1", capture=True, check=False)

    if my_ip and dns_ip and my_ip == dns_ip:
        ok(f"DNS OK — {DOMAIN} → {my_ip}")
    else:
        warn(f"DNS mismatch: {DOMAIN} → {dns_ip or 'NOT RESOLVED'}, Server IP → {my_ip}")
        warn("SSL may fail. You can run it manually later.")

    result = run(
        f"certbot --nginx -d {DOMAIN} -d www.{DOMAIN} "
        f"--email kuchalagteam@gmail.com --agree-tos --no-eff-email --non-interactive",
        check=False
    )

    if result:
        ok("SSL certificate installed!")
        run("certbot renew --dry-run", check=False)
        cron = "0 2 * * * /usr/bin/certbot renew --quiet && systemctl reload nginx"
        run(f'(crontab -l 2>/dev/null | grep -v certbot; echo "{cron}") | crontab -', check=False)
        ok("Auto-renewal cron configured")
    else:
        warn("SSL setup failed — DNS not propagated yet?")
        info(f"Run later: sudo certbot --nginx -d {DOMAIN} -d www.{DOMAIN}")


def step_10_finalize():
    step(10, "Security Hardening & Helper Scripts")

    # fail2ban
    info("Installing fail2ban...")
    run("apt install -y fail2ban", check=False)
    run("systemctl enable fail2ban && systemctl start fail2ban", check=False)
    ok("fail2ban installed")

    # Auto security updates
    run("apt install -y unattended-upgrades", check=False)
    run("dpkg-reconfigure -plow unattended-upgrades -f noninteractive", check=False)

    # ── Redeploy script ──
    redeploy = f"""#!/bin/bash
set -e
echo "🔄 Redeploying backend..."
cd {PROJECT_DIR}/backend
git pull origin main || git pull origin master
npm install --build-from-source=argon2
pm2 restart jwellery-backend
echo "✅ Done!"
pm2 status
"""
    with open(os.path.join(PROJECT_DIR, "redeploy.sh"), "w") as f:
        f.write(redeploy)
    os.chmod(os.path.join(PROJECT_DIR, "redeploy.sh"), 0o755)

    # ── Status script ──
    status = f"""#!/bin/bash
echo ""
echo "═══════════════════════════════════════════"
echo "  {DOMAIN} — Backend Status"
echo "═══════════════════════════════════════════"
echo ""
echo "📊 PM2 Processes:"
pm2 status
echo ""
echo "🌐 Nginx:  $(systemctl is-active nginx)"
echo "🗄️  MongoDB: Atlas (cloud)"
echo ""
echo "💾 Disk:"; df -h / | tail -1 | awk '{{print "   "$3" / "$2" ("$5" used)"}}'
echo "🧠 RAM:";  free -h | awk '/Mem:/ {{print "   "$3" / "$2}}'
echo ""
echo "🔗 API Test:"
curl -s -o /dev/null -w "   Status: %{{http_code}}\\n" https://{DOMAIN}/api/v1/user/get-all-banners 2>/dev/null || echo "   Could not reach API"
echo ""
echo "📋 Vercel Apps:"
echo "   Frontend: https://kuchalagindiarepov2.vercel.app"
echo "   Admin:    https://frontend-jwellery-admin-code-ywsf.vercel.app"
"""
    with open(os.path.join(PROJECT_DIR, "status.sh"), "w") as f:
        f.write(status)
    os.chmod(os.path.join(PROJECT_DIR, "status.sh"), 0o755)

    # ── Logs script ──
    logs = """#!/bin/bash
echo "1) Backend logs  2) Nginx errors  3) All PM2 logs"
read -p "Choice [1-3]: " c
case $c in
    1) pm2 logs jwellery-backend --lines 100 ;;
    2) tail -100 /var/log/nginx/error.log ;;
    3) pm2 logs --lines 50 ;;
    *) echo "Invalid" ;;
esac
"""
    with open(os.path.join(PROJECT_DIR, "logs.sh"), "w") as f:
        f.write(logs)
    os.chmod(os.path.join(PROJECT_DIR, "logs.sh"), 0o755)

    run(f"chown -R {DEPLOY_USER}:{DEPLOY_USER} {PROJECT_DIR}")
    ok("Helper scripts created")


def print_summary():
    print(f"""
{C.G}{C.BD}
╔══════════════════════════════════════════════════════════════════════╗
║                                                                      ║
║              🎉  DEPLOYMENT COMPLETE!  🎉                           ║
║                                                                      ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                      ║
║   🔗 Backend API:    https://{DOMAIN}/api/v1                    ║
║   🔗 Frontend:       https://kuchalagindiarepov2.vercel.app          ║
║   🔗 Admin:          https://frontend-jwellery-admin-code-ywsf...    ║
║                                                                      ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                      ║
║   📂 Files:                                                          ║
║   • Backend code:  {PROJECT_DIR}/backend/                     ║
║   • Environment:   {PROJECT_DIR}/backend/.env                 ║
║   • Redeploy:      {PROJECT_DIR}/redeploy.sh                  ║
║   • Status check:  {PROJECT_DIR}/status.sh                    ║
║   • View logs:     {PROJECT_DIR}/logs.sh                      ║
║                                                                      ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                      ║
║   🛠️  PM2 Commands:                                                  ║
║   • pm2 status                  — See running processes              ║
║   • pm2 logs jwellery-backend   — View backend logs                  ║
║   • pm2 restart jwellery-backend — Restart backend                   ║
║   • pm2 monit                   — Live monitoring                    ║
║   • {PROJECT_DIR}/redeploy.sh  — Pull latest & restart        ║
║                                                                      ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                      ║
║   ⚠️  Vercel Env Vars (set in Vercel Dashboard):                     ║
║                                                                      ║
║   Frontend (Vercel):                                                 ║
║     NEXT_PUBLIC_API_URL         = https://{DOMAIN}              ║
║     NEXT_PUBLIC_IMAGE_BASE_URL  = https://dpd52zzi6t5tf.cloudfront.. ║
║     NEXT_PUBLIC_RAZORPAY_KEY_ID = rzp_live_SagXbIhpAynO7y           ║
║     NEXT_PUBLIC_GOOGLE_CLIENT_ID = 266189706891-kn2efti3o...         ║
║                                                                      ║
║   Admin (Vercel):                                                    ║
║     REACT_APP_BASE_URL   = https://{DOMAIN}                    ║
║     REACT_APP_IMAGE_URL  = https://dpd52zzi6t5tf.cloudfront.net      ║
║     REACT_APP_SHOW_CONSOLE = false                                   ║
║                                                                      ║
║   Default Admin: admin@yopmail.com / Admin@123 ← CHANGE THIS!       ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
{C.RS}""")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MAIN
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def main():
    banner()

    if os.geteuid() != 0:
        err("Must run as root! Use: sudo python3 deploy_backend_vps.py")
        sys.exit(1)

    print(f"""
  {C.BD}{C.Y}Pre-filled Configuration:{C.RS}
  ─────────────────────────────────────────────────
  Domain:     {DOMAIN}
  MongoDB:    Atlas (kuchalag.651c2jx.mongodb.net)
  Email:      kuchalagteam@gmail.com
  AWS S3:     kuch-alag-s3 (ap-south-1)
  Razorpay:   rzp_live_SagXbIhpAynO7y
  JWT:        Auto-generated 64-char secret
  CORS:       7 origins (Vercel + domain + localhost)
  ─────────────────────────────────────────────────
  
  {C.Y}This will install: Node.js 22, Nginx, PM2, SSL, fail2ban{C.RS}
  {C.Y}and deploy the backend Express.js API.{C.RS}
""")

    answer = input(f"  {C.CY}? Start deployment? [Y/n]: {C.RS}").strip().lower()
    if answer in ("n", "no"):
        print("Aborted.")
        sys.exit(0)

    t0 = time.time()

    step_01_update()
    step_02_install()
    step_03_firewall()
    step_04_project()
    step_05_env()
    step_06_build()
    step_07_pm2()
    step_08_nginx()
    step_09_ssl()
    step_10_finalize()

    elapsed = int(time.time() - t0)
    print_summary()
    print(f"\n  {C.G}⏱  Total deployment time: {elapsed // 60}m {elapsed % 60}s{C.RS}\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n{C.Y}  Interrupted. Partial setup may exist.{C.RS}")
        sys.exit(1)
    except Exception as e:
        print(f"\n{C.R}  Fatal: {e}{C.RS}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
